bufferSize: 2048
pages:
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SI499.WAV.n121.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SI499.WAV.n121.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/0db/data/RegressionFCNN_SI499.WAV.n121.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SX139.WAV.n121.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SX139.WAV.n121.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/-25db/data/RegressionFCNN_SX139.WAV.n121.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SA1.WAV.n122.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SA1.WAV.n122.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/-5db/data/RegressionFCNN_SA1.WAV.n122.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SX319.WAV.n122.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SX319.WAV.n122.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/-10db/data/RegressionFCNN_SX319.WAV.n122.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SX409.WAV.n122.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SX409.WAV.n122.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/-30db/data/RegressionFCNN_SX409.WAV.n122.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SX139.WAV.n121.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SX139.WAV.n121.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/0db/data/RegressionFCNN_SX139.WAV.n121.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SI1129.WAV.n121.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SI1129.WAV.n121.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/-25db/data/RegressionFCNN_SI1129.WAV.n121.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SX49.WAV.n121.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SX49.WAV.n121.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/-15db/data/RegressionFCNN_SX49.WAV.n121.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SX319.WAV.n122.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SX319.WAV.n122.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/-15db/data/RegressionFCNN_SX319.WAV.n122.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SI1129.WAV.n122.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SI1129.WAV.n122.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/0db/data/RegressionFCNN_SI1129.WAV.n122.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SI1129.WAV.n121.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SI1129.WAV.n121.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/-20db/data/RegressionFCNN_SI1129.WAV.n121.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SI499.WAV.n122.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SI499.WAV.n122.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/0db/data/RegressionFCNN_SI499.WAV.n122.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SX49.WAV.n122.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SX49.WAV.n122.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/-5db/data/RegressionFCNN_SX49.WAV.n122.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SI1129.WAV.n122.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SI1129.WAV.n122.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/-15db/data/RegressionFCNN_SI1129.WAV.n122.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SI1759.WAV.n121.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SI1759.WAV.n121.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/-25db/data/RegressionFCNN_SI1759.WAV.n121.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SX139.WAV.n121.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SX139.WAV.n121.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/-20db/data/RegressionFCNN_SX139.WAV.n121.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SI499.WAV.n122.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SI499.WAV.n122.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/-15db/data/RegressionFCNN_SI499.WAV.n122.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SI1129.WAV.n122.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SI1129.WAV.n122.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/-20db/data/RegressionFCNN_SI1129.WAV.n122.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SX139.WAV.n121.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SX139.WAV.n121.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/-5db/data/RegressionFCNN_SX139.WAV.n121.wav
  type: paired_comparison
  unforced: null
- content: test description AB
  enableLooping: false
  id: trialAB2
  name: null
  reference: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Clean/clean_SI1129.WAV.n121.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/Drone_Noise_Test_Data//drone_noise_out//Noisy/noisy_SI1129.WAV.n121.wav
    C2: configs/resources/Drone_Noise_Test_Data//drone_noise_out//RegressionFCNN/-10db/data/RegressionFCNN_SI1129.WAV.n121.wav
  type: paired_comparison
  unforced: null
- content: Thank you for attending
  name: Thank you
  showResults: false
  type: finish
  writeResults: true
remoteService: service/write.php
showButtonPreviousPage: true
stopOnErrors: true
testId: ab_noloop
testname: AB Test
